FROM nginx:latest

COPY nginx-wordpress.conf /etc/nginx/conf.d
RUN rm -f /etc/nginx/conf.d/default.conf

RUN rm -f /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx

COPY ../app/wordpress /var/www/html

EXPOSE 80